### ISSUE TITLE
Checklist for v0.0.4

### ISSUE THREAD

**Issue by toriving** [toriving/KoEDA#4]
- [ ] Improve WordNet / Synonyms (NIKLex, KorLex)
  - NIKLex : https://corpus.korean.go.kr/
  - KorLex : http://korlex.pusan.ac.kr/
- [x] Improve README.md
~~docstring~~
- [x] requirements.txt version check (>=)
- [x]  Exception -> ValueError
~~tokenizer selection (if statement or str.lower())~~

**Comment by toriving** [comment]
- [x] Add AEDA (https://github.com/akkarimi/aeda_nlp)

**Comment by toriving** [comment]
~~Benchmark~~
